image: atlassian/default-image:3

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build and Test'
          script:
            - npm install
            - npm start
            - npm test
#      - step:
#          name: 'Lint'
#          script:
#            - eslint src/**/*.js src/**/*.jsx
